import{a as p,S as g,i as c}from"./assets/vendor-CXUzKRcQ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const h="49070628-cf42e4c64cc07d7e6ab81af9e",y="https://pixabay.com/api/";function L(i){const o=`${y}?key=${h}&q=${i}&image_type=photo&orientation=horizontal&safesearch=true`;return p.get(o).then(t=>t.data.hits).catch(t=>{throw console.error("Error fetching data from Pixabay API:",t),t})}function b(i){const o=document.querySelector("#gallery");o.innerHTML="";const t=i.map(({largeImageURL:e,webformatURL:r,tags:n,likes:u,views:d,comments:f,downloads:m})=>`
      <a href="${e}" class="gallery-item">
        <img src="${r}" alt="${n}" />
        <div class="image-info">
          <p><strong>Likes:</strong> ${u}</p>
          <p><strong>Views:</strong> ${d}</p>
          <p><strong>Comments:</strong> ${f}</p>
          <p><strong>Downloads:</strong> ${m}</p>
        </div>
      </a>`).join("");o.innerHTML=t,new g(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:1,showCounter:!1}).refresh()}const s={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loader:document.querySelector("#loader"),gallery:document.querySelector("#gallery")};function P(){s.loader.classList.remove("hidden")}function l(){s.loader.classList.add("hidden")}s.form.addEventListener("submit",i=>{i.preventDefault();const o=s.input.value.trim();if(!o){c.error({title:"Error",message:"Please enter a search term!",position:"topRight",timeout:2e3});return}P(),L(o).then(t=>{l(),t.length===0?c.info({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}):b(t)}).catch(t=>{l(),c.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),console.error("Error fetching images:",t)})});
//# sourceMappingURL=index.js.map
